services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bookstore-api:
    container_name: bookstore-api
    build: . 
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:123@postgres:5432/postgres"
